### PR TITLE
Create Rozena payload.

### PR DESCRIPTION
**Pull request by sqrtZeroKnowledge**
VT: https://www.virustotal.com/gui/file/997684fb438af3f5530b0066d2c9e0d066263ca9da269d6a7e160fa757a51e04

Basic details:

MD5 7a4b1f29bb97c185f84c2e3194c1f21f
SHA-1 5a72a4a25b1be7e51086ffd0090c2a17677d1f98
SHA-256 997684fb438af3f5530b0066d2c9e0d066263ca9da269d6a7e160fa757a51e04
Vhash 04303e0f6d1bz601=z
Authentihash c53255d4ef47fbe75482619127ecfbd461565bc0a43e19aa5d06ccbd3f8573fe
Imphash 4bfd1be901a4c0d571291552b2d7a34c
SSDEEP 48:6dlNRzH3OkFWjpPPmdf77OdmqvipZPaV2/RW97RFdXRxfOyGpaSpEBdNW/6GSeJ2:Al7Dpcj5Pk/Od1vi6jzTGpFELNWirygv
TLSH T18691F8BDA59454BFD42C007613CE95323EBA74A0DBEF87665E08D01A5AB3AA4352CE11
File type Win32 EXE
Magic PE32 executable for MS Windows (console) Intel 80386 32-bit
TrID UPX compressed Win32 Executable (37.1%)
TrID[ Win32 EXE ](https://www.virustotal.com/gui/search/tag%253Apeexe)Yoda's Crypter (36.4%)
TrID Win32 Dynamic Link Library (generic) (9%)
TrID Win32 Executable (generic) (6.1%)
TrID OS/2 Executable (generic) (2.7%)
File size 4.25 KB (4351 bytes)
PEiD packer UPX 2.90 [LZMA] -> Markus Oberhumer, Laszlo Molnar & John Reiser
F-PROT packer UPX

### CODE REVIEW

**Comment by kevoreilly** [comment]
This is a Windows executable - how can the 'threat name' be `Linux.Trojan.Rozena`?

There is still only a single pattern - I've suggested this isn't really enough to prevent FPs and future detection breakages.

What made you choose this particular byte sequence?

image

This sequence contains two constants 0xC7701AA4 and part of 0xE92EADA4 - this is normally extremely poor for detection as these seem to be arbitrary and subject to rapid change across variants. The code does not seem particularly characteristic or unique either, so it's not obvious why it is chosen for detection.

**Comment by sqrtZeroKnowledge** [comment]
> This is a Windows executable - how can the 'threat name' be `Linux.Trojan.Rozena`?
> 
> There is still only a single pattern - I've suggested this isn't really enough to prevent FPs and future detection breakages.
> 
> What made you choose this particular byte sequence?
> 
> image
> 
> This sequence contains two constants 0xC7701AA4 and part of 0xE92EADA4 - this is normally extremely poor for detection as these seem to be subject to rapid change across variants. The code does not seem particularly characteristic or unique either, so it's not obvious why it is chosen for detection.

Sorry its my bad i forgot to change os it is Windows PEexe file not elf.

**Comment by sqrtZeroKnowledge** [comment]
I will gather more samples related to Rozena trojan and define a related detection for it. And than test it again.

**Review by sqrtZeroKnowledge — COMMENTED** [review]
Forgot to change threat name feom Linux.Trojan.Rozena to Windows.Trojan Rozena

**Comment by kevoreilly** [comment]
Yes a few more examples would be good - happy to contribute some detection patterns if needed.

**Pull request closed without merging**
