### PR TITLE
Check if self.compname exists in dyre_apis sig

### PR DESCRIPTION
**Pull request by cccs-kevin**

### CODE REVIEW

**Comment by doomedraven** [comment]
hm dyre is more than dead, maybe we should move this to deprecated folder?

**Comment by cccs-kevin** [comment]
> hm dyre is more than dead, maybe we should move this to deprecated folder?

Do we have that functionality yet in this repo?

**Comment by doomedraven** [comment]
not really, so what would be the best option in your opinion?
1. create folder deprecated with the same structure as other modules: ex: deprecated/signatures
2. add sufix `_deprecated` to .py files so it would be `.py_deprecated`
3. create folder inside of each folder like: `modules/signatures/deprecated`

**Comment by cccs-kevin** [comment]
> not really, so what would be the best option in your opinion?
> 
>     1. create folder deprecated with the same structure as other modules: ex: deprecated/signatures
> 
>     2. add sufix `_deprecated` to .py files so it would be `.py_deprecated`
> 
>     3. create folder inside of each folder like: `modules/signatures/deprecated`
> 
>     4. any better idea/suggestion?

I like option 1 :)

**Comment by doomedraven** [comment]
cool is what im using on my dailyjob, i will push that in a bit

**Pull request merged**
