### PR TITLE
Add and updaet Yara signatures

### PR DESCRIPTION
**Pull request by ditekshen**
QuasarStealer:
https://capesandbox.com/analysis/108045/
https://capesandbox.com/analysis/108044/

Amady  (I had this updated but forgot to PR):
https://capesandbox.com/analysis/107939/

RansomEXX:
https://capesandbox.com/analysis/108057/

### CODE REVIEW

**Comment by ditekshen** [comment]
Sorry about the mess :)

**Comment by doomedraven** [comment]
np, you making community alive and up to date :) thanks for that

**Comment by doomedraven** [comment]
wait Amady or Amadey?

**Comment by ditekshen** [comment]
Ahh good catch, should be Amadey..Thank you for understanding!

**Comment by doomedraven** [comment]
ok then i corrected it correctly, thanks again

**Comment by ditekshen** [comment]
Great, thank you.

**Pull request merged**
