### PR TITLE
Add and update Yara signatures

### PR DESCRIPTION
**Pull request by ditekshen**
Snake: https://capesandbox.com/analysis/106353/

### CODE REVIEW

**Comment by ditekshen** [comment]
https://capesandbox.com/analysis/106705/

**Comment by doomedraven** [comment]
i didn't deploy them yet

**Comment by ditekshen** [comment]
I know, just digging/documenting the ones I'm finding.. tyt!

**Comment by doomedraven** [comment]
ah thank you, i will sync it in a bit, just finished flare capa integration to community.py

**Comment by kevoreilly** [comment]
As ever your signatures are massively appreciated and make a big difference to CAPE!

**Comment by ditekshen** [comment]
Thank you! Glad to be part of CAPE and contributing some.

**Pull request merged**
