### PR TITLE
add network_questioable_host

### PR DESCRIPTION
**Pull request by VVelox**
This chews through .network looking for anything in a RBL. This seems to work decently as lots of stuff uses hosting providers that are either shit or of questionable reputation.

The only thing I am not to sure about is including spam.dnsbl.sorbs.net. That may be better for a separate check with a bit lower confidence and rating.

### CODE REVIEW

**Comment by VVelox** [comment]
Not just relying on .network.hosts as for some reason sometimes there are other items that the logic that generates it does not feel like including in tcp, icmp, and upd.

**Comment by doomedraven** [comment]
Hello thanks, i did cleanup and by default it disabled, so user should enable it as i don't want nothing doing external connections without user being properly aware of that

**Comment by VVelox** [comment]
@doomedraven Awesome. May seem like a silly question, but how does one disable/enable specific sigs? I don't remember seeing anything about that in the docs or the like.

**Comment by doomedraven** [comment]
you need edit signature en change `enabled = False` to `enabled = True` make config for that would be hard as new sigs are added frequently

**Pull request merged**
