### PR TITLE
Add and update behavior signatures

### PR DESCRIPTION
**Pull request by ditekshen**
infostealer_screenshot.py > https://capesandbox.com/analysis/133191/ > Behavior > Page 63 at 2021-04-08 10:05:49,499

### CODE REVIEW

**Comment by doomedraven** [comment]
yey thanks, can you please fix this?

```
./modules/signatures/network_dns_suspicious.py:482:26: F821 undefined name 'domain_indictors'
        for indicator in domain_indictors:
                         ^
1     F821 undefined name 'domain_indictors'
```

**Comment by ditekshen** [comment]
Yup working on, sorry about that :(

**Comment by doomedraven** [comment]
np, thanks

**Comment by doomedraven** [comment]
thank you

**Pull request merged**
