### PR TITLE
Create bazarloader.yara

### PR DESCRIPTION
**Pull request by r0ny123**

### CODE REVIEW

**Comment by kevoreilly** [comment]
Would you mind renaming to .yar? This is the standard in cape.

**Comment by r0ny123** [comment]
> Would you mind renaming to .yar? This is the standard in cape.

done.

**Comment by kevoreilly** [comment]
Thanks!

**Comment by kevoreilly** [comment]
I fixed the capitalisation too - the standard in cape is to use camel case as you can see in all the other signatures.

**Pull request merged**
