### PR TITLE
Add and update behavior signatures

### PR DESCRIPTION
**Pull request by ditekshen**
https://capesandbox.com/analysis/67881/ > ursnif_api.py did not trigger.

https://capesandbox.com/analysis/67867/ > account_modifications.py

### CODE REVIEW

**Comment by ditekshen** [comment]
I updated this yet I still pushed the wrong copy. Fixing now.

**Comment by doomedraven** [comment]
see build, failed, undefined variable ;)

**Comment by ditekshen** [comment]
Yup, I saw that. Today is not my day! Yay, passed :)

**Comment by doomedraven** [comment]
thank you

**Pull request merged**
