### PR TITLE
Add indicator Office Yara signatures

### PR DESCRIPTION
**Pull request by ditekshen**

### CODE REVIEW

**Comment by doomedraven** [comment]
i will marge that later as i need to ensure that office yara is loaded correctly

**Comment by doomedraven** [comment]
i totally forgot about this working on another subject, did you close it bcz of something specific?

**Comment by ditekshen** [comment]
No worries at all. The PR is outdated at this point, made many changes. Will PR it again once its ready for merge.

**Comment by doomedraven** [comment]
ah cool thanks, i will try to add this just after finish one nice feature that is almost ready ;)

**Comment by ditekshen** [comment]
Thank you. Intriguing, can't wait :)

**Pull request closed without merging**
