### PR TITLE
Update Lu0bot YARA

### PR DESCRIPTION
**Pull request by r0ny123**

### CODE REVIEW

**Comment by kevoreilly** [comment]
Thank you

**Comment by kevoreilly** [comment]
Does this mean the original PR was not tested? Please test these before you PR as I haven't got time to test every PR before merging.

**Comment by r0ny123** [comment]
Yeah no worry, just a small typo, hence the draft. no problem in sig though.

**Comment by r0ny123** [comment]
> Does this mean the original PR was not tested? Please test these before you PR as I haven't got time to test every PR before merging.

Ready to be merged.

**Pull request merged**
