### PR TITLE
Adding the use of mark_call to sigs that use on_call

### PR DESCRIPTION
**Pull request by cccs-kevin**
Dependent on https://github.com/kevoreilly/CAPEv2/pull/1051

### CODE REVIEW

**Comment by doomedraven** [comment]
dyre is moved to deprecated

**Comment by doomedraven** [comment]
Kevin i just spot one thing in signatures, in most of the cases it adds empty fields, i did a quick test and if i add `if self.pid:` then call to mark_call, so that only populates data properly, im gonna try to update those signatures 

```
[A process attempted to delay the analysis task.](https://capesandbox.com/analysis/297569/#signature_antisandbox_sleep)
type: call
pid: None
cid: None
call: None
```

**Comment by cccs-kevin** [comment]
> 

Really? Even with this PR in use https://github.com/kevoreilly/CAPEv2/pull/1051?

**Comment by doomedraven** [comment]
yes even with that, i did update yesterday of whole box. but i think maybe it could be related that i need to restart cape service but i was working on previous data?

**Comment by cccs-kevin** [comment]
> yes even with that, i did update yesterday of whole box. but i think maybe it could be related that i need to restart cape service but i was working on previous data?

Yes I suspect you will have to restart the cape.service because of the changes to the `abstracts.py` file

**Comment by cccs-kevin** [comment]
And restart the cape-processor.service as well

**Comment by doomedraven** [comment]
Ok then problem was that i was on old data,  later i will rever my if change

**Pull request merged**
