### PR TITLE
add adobe, microsoft and digicert hosts to host_whitelist in http_req

### PR DESCRIPTION
**Pull request by AvihayST**
http_request signature

### CODE REVIEW

**Comment by doomedraven** [comment]
i think maybe is time to load the blocklist in here https://github.com/kevoreilly/CAPEv2/blob/master/data/safelist/domains.py so we can have one elaborated central list for network.py and some sigs what do you think?

**Comment by doomedraven** [comment]
please check this 2 commits, they should simplify a lot this

https://github.com/kevoreilly/CAPEv2/commit/e61ca7e276d47bd110efe4e199f10233d91bdf5e
https://github.com/kevoreilly/community/commit/4011e8413027894f3592b55dfc3940acc7db1d9f

thanks for updates

**Comment by AvihayST** [comment]
@doomedraven looking great, love the idea of one place with all the approved domains

**Comment by doomedraven** [comment]
Easier to maintain :)

**Pull request merged**
